### ISSUE TITLE
LUA Settings in Config not completely loading

### ISSUE THREAD

**Issue by nazexd** [Cheese0t/Aimware-Luas#1]
This is considered for the AdvancedChams LUA.

If i save my config with my settings I chose they will appear when loading but not quite apply. the chams change but not the way they should. to do that i will have to select each option of the comboboxes which I had saved my settings from to somehow refresh the chams and apply them correctly. This is quite annoying but I dont know if there's a way to do that differently. I was searching for something that will correctly apply the chams right when loading.

**Comment by Cheese0t** [comment]
Should be fixed with v1.3 at the cost of some performance while the menu is open. If you still have issues with it feel free to add a new issue.
